- hosts: all
  become: true
  gather_facts: false
  vars_files:
    - "vars/dev.yml"
  roles:
#      - initial
#      - php-ubuntu
#      - nginx
#      - phpredis
#      - redis
#      - pgsql
#      - phppgadmin
#      - composer
      - finally